# Generated by Django 4.2 on 2025-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_role_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_posts/'),
        ),
    ]
