[build]
  base = "frontend/my-react-app"
  command = "npm run build"
  publish = "frontend/my-react-app/dist"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

