[build]
  base = "frontend/my-react-app"
  command = "npm run build"
  publish = "build"  # or "dist" if your build output folder is named dist

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
