services:
  - type: web
    name: jobsite-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend/myproject && gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: WSGI_APPLICATION
        value: myproject.wsgi.application
