services:
  - type: web
    name: job  # Changed to match your project name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn job.wsgi:application  # Updated to match your Django project structure
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
